---

- hosts: localhost
  gather_facts: no
  vars:
    dest_dir: /tmp
    dest_file: foo.txt
  tasks:
  - name: create temp file in 
    copy:
       content: "TEST CONTENT"
       dest: "{{ dest_dir }}/{{ dest_file }}"
